Dynamic project and yearbook pages
rubyforgood/rubyforgood.org--old pull request #136
Opened 2017-05-26 00:52 UTC by craig-riecke

- Removed Register button to make room for Projects menu item
- Added Projects page, populated by data in meta repo
- Added Help Wanted page
- Added 2017 Yearbook projects, populated dynamically

2017-05-26 00:53 UTC, seanmarcia commented on _includes/_global_js.html
> +  ga('create', 'UA-77346638-1', 'codefordc.org');
Probably don't want to put in code for dc's google analytics ;)

2017-05-26 00:54 UTC, craig-riecke commented
I tried to fork this repo, but could only get it to host as https://craig-riecke.github.io/rubyforgood.html, which made all the assets and links not work.  So you'll need to set up a local host to see what it actually looks like.

2017-05-26 00:54 UTC, craig-riecke commented on _includes/_global_js.html
> +  ga('create', 'UA-77346638-1', 'codefordc.org');
Good point!

2017-05-26 14:21 UTC, csexton requested changes
Ran things locally and it all looked great. This is really awesome I just have a few nit-picky things I'd like to get cleaned up. 

The projects, yearbook and help wanted pages are absolutely wonderful.

2017-05-26 14:21 UTC, csexton commented on _includes/_global_js.html
> +{% if page.deeplink == true %}
I think we can remove this entire section, no pages currently set `deeplink: true`.

2017-05-26 14:21 UTC, csexton commented on _includes/_global_js.html
> +    });
Local testing it doesn't look like this works/is used. I'd prefer to just delete this snippet.

2017-05-26 14:21 UTC, csexton commented on _includes/_global_js.html
> +{% for js_name in page.extra_js %}<script src="/assets/js/{{ js_name }}"></script>{% endfor %}
Any reason we shouldn't just include the `extra_js` files from the project page in the `base.html` layout?

2017-05-26 14:21 UTC, csexton commented on _includes/_global_js.html
> +<script src="/assets/js/bootstrap.min.js"></script>
Duplicate includes, both bootstrap and jquery are already included in the `base.html` layout.

2017-05-26 14:21 UTC, csexton commented on _includes/_global_js.html
> +  ga('create', 'UA-77346638-1', 'codefordc.org');
I'd just drop the google analytics all together.

2017-05-26 14:21 UTC, csexton commented on _includes/projects-yearbook.html
> +{% include _global_js.html %}
Looks like there are duplicate includes in this file.

2017-05-26 14:21 UTC, csexton commented on _layouts/base.html
> +  {% for css_name in page.extra_css %}<link rel="stylesheet" href="/assets/css/{{ css_name }}">{% endfor %}
Just like the JS: No need to special case the CSS includes, we should just load them all in `base.html`

2017-05-26 14:21 UTC, csexton commented on helpwanted.html
> +</script>
I love this page! Nice work :heart:

2017-05-29 19:35 UTC, craig-riecke commented
All righty, I took all of your suggestions.  It turns out the _global.js stuff was funky due to page loading timing issues.  Once I fixed those, _global.js wasn't needed anymore so I removed it.   Lemme know if anything is still amiss.

2017-05-30 15:07 UTC, csexton approved these changes
Thanks for the updates @craig-riecke, much simpler. I ran everything locally and it all looked great -- even the new slack section on the project page.

:shipit:

2017-05-30 15:58 UTC, merged